version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    ports:
      - "8181:1433"


  
  najotnur:
    image: ${DOCKER_REGISTRY-}najotnur
    build:
      context: .
      dockerfile: NajotNur/Dockerfile
