version: '3.4'

services:
  najotnur:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"